# Generated by Django 3.2 on 2021-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('hospital', models.CharField(choices=[('Aga Khan', 'Agha Khan'), ('Liaquat National', 'Liaquat National'), ('Essa Lab', 'Essa Lab'), ('South City', 'South City')], max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
    ]
