# Generated by Django 3.2 on 2021-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_medicaldata_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='covidStatus',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='Diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='HIV',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='Seizures',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
    ]
