# Generated by Django 3.2 on 2021-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210816_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='covidStatus',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Pending', max_length=50, null=True),
        ),
    ]
