# Generated by Django 3.2 on 2021-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_alter_medicaldata_covidstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='covidStatus',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
